[package]
name = "aoc-2022-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.test]
opt-level = 3

[profile.bench]
debug = true

[dependencies]
pathfinding = "4.1"
serde_json = "1"
test-case = "2.2"
