[package]
name = "aoc-2022-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4"
serde_json = "1.0.89"
test-case = "2"
